name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add rust-src component
      run: rustup component add rust-src
    - name: Install Polkatool
      run: cargo install polkatool --version 0.26.0
    - uses: actions/checkout@v4
    - name: Build
      run: make
